#Mandatory config elements
floor_count=3
sectors_per_floor=10
small_spaces=300
medium_spaces=300
large_spaces=300

# A GIVEN FLOOR CAN BE DESIGNED WITH THESE VARIABLE
# NOTE THE TOTAL AMOUNT OF FLOORS MUST ALWAYS BE THE SAME AS IN THE MANDETORY CONFIG AREA
# floor1_spaces_small=10
# floor1_spaces_medium=10
# floor1_spaces_large=10
# floor1_spaces_electric=10
# floor1_spaces_disabled=10

floor1_spaces_small=40
floor1_spaces_medium=100
floor1_spaces_large=100
floor1_spaces_electric=50
floor1_spaces_disabled=10

floor2_spaces_small=100
floor2_spaces_medium=100
floor2_spaces_large=100
floor2_spaces_electric=0
floor2_spaces_disabled=0

floor3_spaces_small=100
floor3_spaces_medium=100
floor3_spaces_large=100
floor3_spaces_electric=0
floor3_spaces_disabled=0